// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOnjYC8FgHmXyYcGd5CD4FyRh9dPWJa0o',
    appId: '1:1033559801370:web:eb30dd392f1cf3e24b1ba3',
    messagingSenderId: '1033559801370',
    projectId: 'doctor-management-portal',
    databaseURL:
        'https://doctor-management-portal-default-rtdb.firebaseio.com/',
    authDomain: 'doctor-management-portal.firebaseapp.com',
    storageBucket: 'doctor-management-portal.appspot.com',
    measurementId: 'G-02KKHE4VSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEdSg-wxBYyJ9zrpUFlKDNWBiz78PU6Wk',
    appId: '1:1033559801370:android:7306632fa8f8bebc4b1ba3',
    messagingSenderId: '1033559801370',
    databaseURL:
        'https://doctor-management-portal-default-rtdb.firebaseio.com/',
    projectId: 'doctor-management-portal',
    storageBucket: 'doctor-management-portal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8s5X2ouKLs0-Fj9VRLUFwXHjCJr3A3Q8',
    appId: '1:1033559801370:ios:c2e79023265f710f4b1ba3',
    messagingSenderId: '1033559801370',
    projectId: 'doctor-management-portal',
    storageBucket: 'doctor-management-portal.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8s5X2ouKLs0-Fj9VRLUFwXHjCJr3A3Q8',
    appId: '1:1033559801370:ios:0c609197d487fc004b1ba3',
    messagingSenderId: '1033559801370',
    projectId: 'doctor-management-portal',
    storageBucket: 'doctor-management-portal.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
